services:
  db:
    image: postgres:13
    container_name: niyat-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: niyat
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend_service:
    depends_on:
      - db
    build:
      context: .
    image: phoenix_bot_image
    container_name: phoenix_bot_container
    env_file:
      - .env

volumes:
  pgdata: {}  # Определение тома
